# Spring Journey

This directory is a practical guide that follows https://spring.io/guides#getting-started-guides[spring guides]


## 1. https://spring.io/guides/gs/rest-service/[Building a RESTful Web Service]

The service will handle GET request for `/greeting`, optionally with a `name` parameter in the query string. The GET request should return `200 OK` response with JSON in the body that represents a greeting. it looks like the following output:
[source, json]
----
{
    "id": 1,
    "content": "Hello, World!"
}
----

### Run command

`./gradlew build && java -jar build/libs/01-building-restful-web-service-0.0.1-SNAPSHOT.jar`

Let's have a close look in the command.

1. `./gradlw build`: build the java code as jar package
2. `java -jar build/libs/xx.jar`: execute the jar


## 2. https://spring.io/guides/gs/scheduling-tasks/[Scheduling tasks]

The service will execute the given task every period of time. In our case, it prints the current time every 5000 milliseconds.


[source, java]
----
@EnableScheduling // This is to enable scheduling ability for our application.
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

}
----

[source, java]
----
 /**
     * Executes the task every 5000 milliseconds
     */
    @Scheduled(fixedRate = 5000)
    public void reportCurrentTime(){
        LOGGER.info("The time is now {}", dataFormat.format(new Date()));
    }
----


## 3. https://spring.io/guides/gs/consuming-rest/[consuming-web-service]

Creates a service that consumes a RESTful web service.

[source,java]
----
  @Bean
    public RestTemplate restTemplate(RestTemplateBuilder builder) {
        return builder.build();
    }


    @Bean
    public CommandLineRunner run(RestTemplate restTemplate) throws Exception {
        return args -> {
            logger.info("Command runner starting to work...");
            Quote quote = restTemplate.getForObject(
                    "https://quoters.apps.pcfone.io/api/random", Quote.class);
            logger.info("Command runner receives [{}]", quote.toString());
        };
    }
----

When the application startup, the commandRunner will send a GET request to `https://quoters.apps.pcfone.io/api/random` that returns a quote as bellows:

**Quote{type='success', value=Value{id=1, quote='Working with Spring Boot is like pair-programming with the Spring developers.'}}**



