# Spring Journey

This directory is a practical guide that follows https://spring.io/guides#getting-started-guides[spring guides]


## 1. https://spring.io/guides/gs/rest-service/[Building a RESTful Web Service]

The service will handle GET request for `/greeting`, optionally with a `name` parameter in the query string.
The GET request should return `200 OK` response with JSON in the body that represents a greeting. it looks like the following output:

[source,json]
----
{
    "id": 1,
    "content": "Hello, World!"
}
----

### Run command

`./gradlew build && java -jar build/libs/01-building-restful-web-service-0.0.1-SNAPSHOT.jar`

Let's have a close look in the command.

1. `./gradlw build`: build the java code as jar package
2. `java -jar build/libs/xx.jar`: execute the jar

## 2. https://spring.io/guides/gs/scheduling-tasks/[Scheduling tasks]

The service will execute the given task every period of time.
In our case, it prints the current time every 5000 milliseconds.

[source,java]
----
@EnableScheduling // This is to enable scheduling ability for our application.
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

}
----

[source,java]
----
 /**
     * Executes the task every 5000 milliseconds
     */
    @Scheduled(fixedRate = 5000)
    public void reportCurrentTime(){
        LOGGER.info("The time is now {}", dataFormat.format(new Date()));
    }
----

## 3. https://spring.io/guides/gs/consuming-rest/[consuming-web-service]

Creates a service that consumes a RESTful web service.

[source,java]
----
  @Bean
    public RestTemplate restTemplate(RestTemplateBuilder builder) {
        return builder.build();
    }


    @Bean
    public CommandLineRunner run(RestTemplate restTemplate) throws Exception {
        return args -> {
            logger.info("Command runner starting to work...");
            Quote quote = restTemplate.getForObject(
                    "https://quoters.apps.pcfone.io/api/random", Quote.class);
            logger.info("Command runner receives [{}]", quote.toString());
        };
    }
----

When the application startup, the commandRunner will send a GET request to `https://quoters.apps.pcfone.io/api/random` that returns a quote as bellows:

**Quote{type='success', value=Value{id=1, quote='Working with Spring Boot is like pair-programming with the Spring developers.'}}**

## 4. https://spring.io/guides/gs/relational-data-access/[Accessing Relational Data using JDBC with Spring]

This service is to illustrate how to access relational data with Spring using JDBCTemplate.

[source,groovy]
----
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    runtimeOnly 'com.h2database:h2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
----

[source,java]
----
    @Override
    public void run(String... args) throws Exception {
        logger.info("Creating tables...");


        jdbcTemplate.execute("DROP TABLE customers IF EXISTS");
        jdbcTemplate.execute("CREATE TABLE customers(" +
                "id SERIAL, first_name VARCHAR(255), last_name VARCHAR(255))");
        // Split up the array of whole names into an array of first/last names
        List<Object[]> splitUpNames = Arrays.asList("John Woo", "Jeff Dean", "Josh Bloch", "Josh Long").stream()
                .map(name -> name.split(" "))
                .collect(Collectors.toList());

        // Use a Java 8 stream to print out each tuple of the list
        splitUpNames.forEach(name -> logger.info(String.format("Inserting customer record for %s %s", name[0], name[1])));

        // Uses JdbcTemplate's batchUpdate operation to bulk load data
        jdbcTemplate.batchUpdate("INSERT INTO customers(first_name, last_name) VALUES (?,?)", splitUpNames);

        logger.info("Querying for customer records where first_name = 'Josh':");
        jdbcTemplate.query(
                "SELECT id, first_name, last_name FROM customers WHERE first_name = ?", new Object[] { "Josh" },
                (rs, rowNum) -> new Customer(rs.getLong("id"), rs.getString("first_name"), rs.getString("last_name"))
        ).forEach(customer -> logger.info(customer.toString()));
    }
----

## 5. https://spring.io/guides/gs/uploading-files/[Uploading Files]

This service is to demonstrate how to create a server application that can receive HTTP multi-part file uploads.
You can run through the code to get details.

## 6. https://spring.io/guides/gs/authenticating-ldap/[Authenticating a User with LDAP]

1. Adds dependencies

[source,groovy]
----

implementation "org.springframework.boot:spring-boot-starter-security"
implementation "org.springframework.ldap:spring-ldap-core"
implementation "org.springframework.security:spring-security-ldap"
implementation "com.unboundid:unboundid-ldapsdk"
----

2. Congiures web security

[source, java]
----

@Configuration
public class WebSecurityConfig  extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .authorizeRequests()
                .anyRequest().fullyAuthenticated()
                .and()
                .formLogin();
    }

    @Override
    public void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth
                .ldapAuthentication()
                .userDnPatterns("uid={0},ou=people")
                .groupSearchBase("ou=groups")
                .contextSource()
                .url("ldap://localhost:8389/dc=springframework,dc=org")
                .and()
                .passwordCompare()
                .passwordEncoder(new BCryptPasswordEncoder())
                .passwordAttribute("userPassword");
    }
}
----

3. add properties and ldif file

[source, yaml]
----
spring.ldap.embedded.ldif=classpath:test-server.ldif
spring.ldap.embedded.base-dn=dc=springframework,dc=org
spring.ldap.embedded.port=8389
----

link:06-authenticating-with-ldap/src/main/resources/test-server.ldif[test-server.ldif]

## 7. https://spring.io/guides/gs/messaging-redis/#initial[messaging with redis]

This service went through the process of using Spring Data Redis to publish and subscribe to messages sent with Redis.


### Standing up a Redis server
Before you can build a messaging application, you need to set up the server that will handle receiving and sending messages.

Redis is an open source, BSD-licensed, key-value data store that also comes with a messaging system. The server is freely available at https://redis.io/download. You can download it manually, or, if you use a Mac, with Homebrew, by running the following command in a terminal window:
[source, bash]
----
// installing redis by using brew
brew install redis

//bring up the redis service
redis-server
----


### Register the listener and Send a Message
[source, java]
----
private static final Logger logger =
            LoggerFactory.getLogger(MessagingWithRedisApplication.class);

    /**
     * Defines MessageListenerContainer
     * @param connectionFactory
     * @param listenerAdapter
     * @return
     */
    @Bean
    RedisMessageListenerContainer container(RedisConnectionFactory connectionFactory,
                                            MessageListenerAdapter listenerAdapter) {
        RedisMessageListenerContainer container
                = new RedisMessageListenerContainer();

        container.setConnectionFactory(connectionFactory);
        container.addMessageListener(listenerAdapter, new PatternTopic("chat"));

        return container;
    }

    /**
     * Registers a message listener that's to be used in `container()` method. and will listen
     * to the `chat` topic.
     *
     * Because of `Receiver` class is a POJO, it needs to be wrapped in a message listener adapter
     * that implements the `MessageListener` interface(which is required by `addMessageListener()`)
     *
     * The message listener adapter is also configured to call the `receiveMessage()` method on `Receiver`
     * when a message arrives.
     *
     * @param receiver
     * @return
     */
    @Bean
    MessageListenerAdapter listenerAdapter(Receiver receiver) {
        return new MessageListenerAdapter(receiver, "receiveMessage");
    }

    /**
     * customized Receiver
     * @return
     */
    @Bean
    Receiver receiver(){
        return new Receiver();
    }

    /**
     * `StringRedisTemplate` is an implementation of `RedisTemplate` that is focused on the
     * common use of Reids, where both keys and values are `String` instances.
     * @param connectionFactory
     * @return
     */
    @Bean
    StringRedisTemplate template(RedisConnectionFactory connectionFactory) {
        return new StringRedisTemplate(connectionFactory);
    }

    public static void main(String[] args) throws InterruptedException {
        ConfigurableApplicationContext ctx =
                SpringApplication.run(MessagingWithRedisApplication.class, args);
        StringRedisTemplate template = ctx.getBean(StringRedisTemplate.class);
        Receiver receiver = ctx.getBean(Receiver.class);

        while (receiver.getCount() == 0) {

            logger.info("Sending message...");
            template.convertAndSend("chat", "Hello from Redis!");
            Thread.sleep(500L);
        }

        System.exit(0);
    }
----

